"""File storage abstraction.

`LocalStorageProvider` is the only implementation shipped today (files land
under `backend/uploads/`, gitignored). Swapping to S3-compatible storage
later means writing one new `StorageProvider` implementation and changing
`STORAGE_PROVIDER` — no call site elsewhere in the app changes.
"""

from abc import ABC, abstractmethod
from pathlib import Path

from app.core.config import get_settings
from app.core.exceptions import AppError


class StorageProvider(ABC):
    @abstractmethod
    def save(self, storage_key: str, content: bytes) -> None:
        raise NotImplementedError

    @abstractmethod
    def read(self, storage_key: str) -> bytes:
        raise NotImplementedError

    @abstractmethod
    def delete(self, storage_key: str) -> None:
        raise NotImplementedError


class LocalStorageProvider(StorageProvider):
    def __init__(self, base_dir: str | None = None) -> None:
        settings = get_settings()
        self._base_dir = Path(base_dir or settings.local_storage_dir).resolve()
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def _resolve(self, storage_key: str) -> Path:
        # storage_key is always generated by generate_storage_key() (uuid
        # prefix + sanitized name) — never taken from raw user input — but
        # we still defend in depth against path traversal here.
        path = (self._base_dir / storage_key).resolve()
        if self._base_dir not in path.parents and path != self._base_dir:
            raise AppError("Invalid storage key.")
        return path

    def save(self, storage_key: str, content: bytes) -> None:
        self._resolve(storage_key).write_bytes(content)

    def read(self, storage_key: str) -> bytes:
        return self._resolve(storage_key).read_bytes()

    def delete(self, storage_key: str) -> None:
        path = self._resolve(storage_key)
        path.unlink(missing_ok=True)


def get_storage_provider() -> StorageProvider:
    settings = get_settings()
    if settings.storage_provider == "local":
        return LocalStorageProvider()
    raise NotImplementedError(
        f"Storage provider '{settings.storage_provider}' is not implemented yet. "
        "Implement a StorageProvider subclass (e.g. S3StorageProvider) in "
        "app/services/storage.py."
    )
